ApiVersion: v1
nodeGroups:
  platform:
    instances:
      architecture: "amd64"
      categories:
      - c
      - m
      - r
      cores:
      - "4"
      - "8"
      - "16"
    amiFamily: Bottlerocket
    amiSelectorTerms:
      - alias: bottlerocket@latest
    nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: platform

