# Helm chart values
tolerations:
  - key: CriticalAddonsOnly
    operator: "Exists"
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: node-role.kubernetes.io/addons
              operator: In
              values: ["true"]
certController:
  tolerations:
    - key: CriticalAddonsOnly
      operator: "Exists"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node-role.kubernetes.io/addons
                operator: In
                values: ["true"]
webhook:
  tolerations:
    - key: CriticalAddonsOnly
      operator: "Exists"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node-role.kubernetes.io/addons
                operator: In
                values: ["true"]