# nodeClases:
#    role: test
#    clusterName: hub-cluster
#    classes:
#     nodeclassx:
#         blockDeviceMappings:
#           - deviceName: /dev/xvda
#             ebs:
#               volumeSize: 100Gi
#               volumeType: gp3
#               iops: 10000
#               encrypted: true
#               deleteOnTermination: true
#               throughput: 125
        # metadataOptions:
        #   httpEndpoint: enabled
        #   httpProtocolIPv6: disabled
        #   httpPutResponseHopLimit: 1 # This is changed to disable IMDS access from containers not on the host network
        #   httpTokens: required
#     nodeclassy:
#       amiFamily: Bottlerocket
#       amiSelectorTerms:
#         - alias: bottlerocket@latest
# nodePools:
#     nodePool1:
#       nodeClassName: nodeclass1
#       labels: 
#         billing-team: my-team
#       annotations:
#         example.com/owner: my-team
#       requirements:
#         - key: "karpenter.k8s.aws/instance-category"
#           operator: In
#           values: ["c", "m", "r"]
#         - key: "karpenter.k8s.aws/instance-cpu"
#           operator: In
#           values: ["4", "8", "16", "32"]
#         - key: "karpenter.k8s.aws/instance-hypervisor"
#           operator: In
#           values: ["nitro"]
#         - key: "karpenter.k8s.aws/instance-generation"
#           operator: Gt
#           values: ["2"]
#       limits:
#         cpu: "2000"
#         memory: 2000Gi
#     nodePool2:
#       nodeClassName: nodeclass2
#       labels: 
#         billing-team: my-team
#       annotations:
#         example.com/owner: my-team
#       requirements:
#         - key: "karpenter.k8s.aws/instance-category"
#           operator: In
#           values: ["c", "m", "r"]
#         - key: "karpenter.k8s.aws/instance-cpu"
#           operator: In
#           values: ["4", "8", "16", "32"]
#         - key: "karpenter.k8s.aws/instance-hypervisor"
#           operator: In
#           values: ["nitro"]
#         - key: "karpenter.k8s.aws/instance-generation"
#           operator: Gt
#           values: ["2"]
#       limits:
#         cpu: "2000"
#         memory: 2000Gi