nodeClases:
  classes:
    nodeClass:
        blockDeviceMappings:
          - deviceName: /dev/xvda
            ebs:
              volumeSize: 100Gi
              volumeType: gp3
              iops: 10000
              encrypted: true
              deleteOnTermination: true
              throughput: 125
# Node Pools Values
nodePools:
    addonsPool:
      nodeClassName: nodeClass
      labels: 
        billing-team: platform-team
        node-role.kubernetes.io/addons: "true"
      annotations:
        example.com/owner: platform-team
      taints:
        - key: CriticalAddonsOnly
          effect: NoSchedule
      requirements:
        - key: "karpenter.k8s.aws/instance-category"
          operator: In
          values: ["c", "m", "r"]
        - key: "karpenter.k8s.aws/instance-cpu"
          operator: In
          values: ["4", "8", "16", "32"]
        - key: "karpenter.k8s.aws/instance-hypervisor"
          operator: In
          values: ["nitro"]
        - key: "karpenter.k8s.aws/instance-generation"
          operator: Gt
          values: ["2"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["spot","on-demand"] 
      limits:
        cpu: "2000"
        memory: 2000Gi
    applicationPool:
      nodeClassName: nodeClass
      labels: 
        billing-team: developers-team
      annotations:
        example.com/owner: developets-team
      requirements:
        - key: "karpenter.k8s.aws/instance-category"
          operator: In
          values: ["c", "m", "r"]
        - key: "karpenter.k8s.aws/instance-cpu"
          operator: In
          values: ["4", "8", "16", "32"]
        - key: "karpenter.k8s.aws/instance-hypervisor"
          operator: In
          values: ["nitro"]
        - key: "karpenter.k8s.aws/instance-generation"
          operator: Gt
          values: ["2"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["spot","on-demand"] 
      limits:
        cpu: "2000"
        memory: 2000Gi
