labels:
  addon: "true"
syncPolicyAppSet:
  preserveResourcesOnDeletion: true
goTemplate: true
goTemplateOptions: ["missingkey=error"]
stackPathPrefix: 'k8s-v'
stackPath: 'addons-{{- $tenant := default dict (index .tenants .metadata.labels.tenant) -}}
          {{- $cluster := index (default dict (index $tenant "clusters")) .name -}}
          {{- $env := index (default dict (index $tenant "environments")) .metadata.labels.environment -}}
          {{- if $cluster -}}
            {{ $cluster.addons_version }}
          {{- else if $env -}}
            {{ $env.addons_version }}
          {{- else if $tenant -}}
            {{ $tenant.addons_version }}
          {{- else -}}
            {{ .addons_version }}
          {{- end -}}.yaml'
stackPathConfigPrefix: 'k8s-v'
stackPathConfig: 'addons-config.yaml'
repoURLGit: "'{{.metadata.annotations.addons_repo_url}}'"
repoURLGitRevision: HEAD
repoURLGitBasePath: "stacks/"
repoURLValues: "'{{.metadata.annotations.addons_repo_url}}'"
repoURLValuesRevision: HEAD
repoURLValuesBasePath: ""
project: default
namespace: argocd
useSelector: false
useStack: false
useStackChart: true
syncPolicy:
  automated:
    selfHeal: false
    allowEmpty: true
    prune: false
  retry:
    limit: -1 # number of failed sync attempt retries; unlimited number of attempts if less than 0
    backoff:
      duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
      factor: 2 # a factor to multiply the base duration after each failed retry
      maxDuration: 10m # the maximum amount of time allowed for the backoff strategy
  syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true  # Big CRDs.
valueFiles:
  - default/addons
  - environments/{{.metadata.labels.environment}}/addons
  - clusters/{{.nameNormalized}}/addons
valueFilesResources:
  - environments/{{.metadata.labels.environment}}/addons
  - clusters/{{.nameNormalized}}/addons
useValuesFilePrefix: false
valuesFilePrefix: tenants/{{.metadata.labels.tenant}}/
addons:
  argocd:
    enabled: false
    releaseName: argocd
    namespace: argocd
    chart: argo-cd
    repoUrl: https://argoproj.github.io/argo-helm
    targetRevision: "7.5.2"
    selector:
      matchExpressions:
        - key: enable_argocd
          operator: In
          values: ['true']
