{{- range $nodePoolName, $nodePool := .Values.nodePools}}
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: {{ $nodePoolName }}
spec:
  template:
    {{- if or $nodePool.labels $nodePool.annotations }}
    metadata:
      {{- if $nodePool.labels }}
      labels:
        {{- range $key, $value := $nodePool.labels }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
      {{- end }}
      {{- if $nodePool.annotations }}
      annotations:
        {{- range $key, $value := $nodePool.annotations }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
      {{- end }}
    {{- end }}
    spec:
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: {{ $nodePool.nodeClassName | default "default" }}
    {{- if $nodePool.taints}}
      taints:
        {{- $nodePool.taints| toYaml | nindent 10  }}
    {{- end }}
    {{- if $nodePool.startupTaints}}
      startupTaints:
            {{- $nodePool.startupTaints| toYaml | nindent 10  }}
    {{- end }}
      requirements:
        {{- $nodePool.requirements  | toYaml | nindent 7  }}
    {{- if $nodePool.limits }}
  limits:
      {{- $nodePool.limits | toYaml | nindent 6  }}
  {{- else }}
  limits:
    cpu: "1000"
    memory: 1000Gi
  {{- end }}
---
{{- end }}