---
{{- if .Values.nodePool.enabled | default false }}
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: {{ .Values.nodePool.name | default "default" }}
spec:
  template:
    {{- if or .Values.nodePool.labels .Values.nodePool.annotations }}
    metadata:
      {{- if .Values.nodePool.labels }}
      labels:
        {{- range $key, $value := .Values.nodePool.labels }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
      {{- end }}
      {{- if .Values.nodePool.annotations }}
      annotations:
        {{- range $key, $value := .Values.nodePool.annotations }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
      {{- end }}
    {{- end }}
    spec:
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: {{ .Values.nodePool.nodeClassName | default "default" }}
    {{- if .Values.nodePool.taints}}
      taints:
        {{- .Values.nodePool.taints| toYaml | nindent 10  }}
    {{- end }}
    {{- if .Values.nodePool.startupTaints}}
      startupTaints:
            {{- .Values.nodePool.startupTaints| toYaml | nindent 10  }}
    {{- end }}
      requirements:
        {{- .Values.nodePool.requirements  | toYaml | nindent 7  }}
    {{- if .Values.nodePool.limits }}
  limits:
      {{- .Values.nodePool.limits | toYaml | nindent 6  }}
  {{- else }}
  limits:
    cpu: "1000"
    memory: 1000Gi
  {{- end }}
{{- end }}
