apiVersion: iam.services.k8s.aws/v1alpha1
kind: Role
metadata:
  name: {{ include "pod-identity.fullname" . }}
spec:
  name: {{ include "pod-identity.fullname" . }}
  assumeRolePolicyDocument: |
    {
        "Version": "2012-10-17",
        "Statement": [
            {
                "Effect": "Allow",
                "Principal": {
                    "Service": "pods.eks.amazonaws.com"
                },
                "Action": [
                    "sts:TagSession",
                    "sts:AssumeRole"
                ]
            }
        ]
    }
  description: {{ .Values.podIdentityRole.description }}
  {{- if .Values.podIdentityRole.inlinePolicies }}
  inlinePolicies:
    {{ .Values.podIdentityRole.inlinePolicies | toYaml | nindent 4 }}
  {{- end }}
  {{- if or .Values.podIdentityPolicy.create .Values.podIdentityPolicy.additionalPolicies }}
  {{- if .Values.podIdentityPolicy.create }}
  policyRefs:
    - from:
        name: {{ include "pod-identity.fullname" . }}
    {{- end }}
  {{- if .Values.podIdentityPolicy.additionalPolicies }}
  policies:
    {{- range .Values.podIdentityPolicy.additionalPolicies }}
    - {{ . }}
    {{- end }}
  {{- end }}
  {{- end }}
  {{- if .Values.podIdentityRole.tags }}
  tags:
    {{ .Values.podIdentityRole.tags | toYaml | nindent 4 }}
  {{- end }}
