podIdentityRole:
  description: "EFS CSI Default Role"
podIdentityPolicy:
  description: "EFS CSI Default Policy"
  policies:
    - resourceType: ec2
      resourceName: "*"
      actions:
        - "ec2:DescribeAvailabilityZones"
    - resourceType: elasticfilesystem
      resourceName: "*"
      actions:
        - "elasticfilesystem:DescribeAccessPoints"
        - "elasticfilesystem:DescribeFileSystems"
        - "elasticfilesystem:DescribeMountTargets"
    - resourceType: elasticfilesystem
      resourceName: "*"
      actions:
        - "elasticfilesystem:CreateAccessPoint"
        - "elasticfilesystem:DeleteAccessPoint"
